repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["."]

  - repo: local
    hooks:
      - id: pytest
        name: pytest all
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        types: [python]

