"""edit User model

Revision ID: 523dd35cc608
Revises: 9ade217f9d90
Create Date: 2025-08-25 16:58:47.000619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523dd35cc608'
down_revision: Union[str, Sequence[str], None] = '9ade217f9d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clips')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_requests', sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('track_requests_track_id_fkey'), 'track_requests', 'tracks', ['track_id'], ['id'])
    op.create_table('tracks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tracks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('artist', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tracks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('clips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clip_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('clip_start_sec', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clip_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('clips_track_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('clips_pkey'))
    )
    # ### end Alembic commands ###
