"""add uq_indx trac_request

Revision ID: 7a452950c48c
Revises: 6f2880340618
Create Date: 2025-08-27 19:03:47.530186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a452950c48c'
down_revision: Union[str, Sequence[str], None] = '6f2880340618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_query', 'track_requests', ['user_id', 'query_text'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_query', 'track_requests', type_='unique')
    # ### end Alembic commands ###
