"""add fk_track_request -> track.id

Revision ID: 9ade217f9d90
Revises: 98d11da3e033
Create Date: 2025-08-24 15:29:38.343634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ade217f9d90'
down_revision: Union[str, Sequence[str], None] = '98d11da3e033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'created_at')
    op.add_column('track_requests', sa.Column('track_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'track_requests', 'tracks', ['track_id'], ['id'])
    op.drop_column('track_requests', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_requests', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'track_requests', type_='foreignkey')
    op.drop_column('track_requests', 'track_id')
    op.add_column('clips', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
