"""refactoring

Revision ID: 77cc69e7979e
Revises: 7a452950c48c
Create Date: 2025-09-02 22:56:53.759968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cc69e7979e'
down_revision: Union[str, Sequence[str], None] = '7a452950c48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('track_name_registry_user_id_fkey'), 'track_name_registry', type_='foreignkey')
    op.create_foreign_key(None, 'track_name_registry', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('track_requests_user_id_fkey'), 'track_requests', type_='foreignkey')
    op.create_foreign_key(None, 'track_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track_requests', type_='foreignkey')
    op.create_foreign_key(op.f('track_requests_user_id_fkey'), 'track_requests', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'track_name_registry', type_='foreignkey')
    op.create_foreign_key(op.f('track_name_registry_user_id_fkey'), 'track_name_registry', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
