"""restore relationship

Revision ID: 6f2880340618
Revises: 523dd35cc608
Create Date: 2025-08-25 17:05:55.792915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2880340618'
down_revision: Union[str, Sequence[str], None] = '523dd35cc608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_requests', 'track_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_requests', sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
