logging:
  level: DEBUG #INFO
  format: "%(asctime)s | %(levelname)-8s | %(funcName)s:%(lineno)d | %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG #INFO
      stream: ext://sys.stdout

    file_app:
      class: logging.FileHandler
      filename: logs/backend.log
      level: DEBUG #INFO
      filters: [ own_logger_filter ]

    file_sqlalchemy:
      class: logging.FileHandler
      filename: logs/sqlalchemy.log
      level: DEBUG #INFO

    file_redis:
      class: logging.FileHandler
      filename: logs/redis.log
      level: DEBUG #INFO

  filters:
    own_logger_filter:
      (): src.service.settings.logger.filters.OwnLoggerFilter
      allowed_loggers_prefixes:
        - "src."       # если используешь структуру проекта с src/
        - "__main__"   # если запускаешь как скрипт

  loggers:
    root:
      handlers: [ console, file_app ]
      level: DEBUG #INFO
      propagate: false

    aiogram:
      handlers: [ console, file_app ]
      level: DEBUG #INFO
      propagate: false

    sqlalchemy:
      handlers: [ file_sqlalchemy ]
      level: DEBUG #INFO
      propagate: false

    redis:
      handlers: [ file_redis ]
      level: DEBUG #INFO
      propagate: false

    aioredis:
      handlers: [ file_redis ]
      level: DEBUG #INFO
      propagate: false
